- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine
  apt:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd.io
    state: latest
    update_cache: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user != "root"

- name: Log in to DockerHub
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"
